// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfokKGCEYXByl8bO4fn4Oo55B7g6ctrKw',
    appId: '1:757571552144:web:ad83737f4e4931dddc2915',
    messagingSenderId: '757571552144',
    projectId: 'pizza-delivery-66670',
    authDomain: 'pizza-delivery-66670.firebaseapp.com',
    storageBucket: 'pizza-delivery-66670.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiWI9WSgPbzYBpID0niw7_J6Pa31X5j4',
    appId: '1:757571552144:android:d07952693ce9ce0bdc2915',
    messagingSenderId: '757571552144',
    projectId: 'pizza-delivery-66670',
    storageBucket: 'pizza-delivery-66670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjUrxjcgW4hHNTrTyGbabDZZHkYmELdOI',
    appId: '1:757571552144:ios:d967f1373ca8a4d4dc2915',
    messagingSenderId: '757571552144',
    projectId: 'pizza-delivery-66670',
    storageBucket: 'pizza-delivery-66670.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjUrxjcgW4hHNTrTyGbabDZZHkYmELdOI',
    appId: '1:757571552144:ios:ee3743505c8e1c00dc2915',
    messagingSenderId: '757571552144',
    projectId: 'pizza-delivery-66670',
    storageBucket: 'pizza-delivery-66670.appspot.com',
    iosBundleId: 'com.example.pizzaApp.RunnerTests',
  );
}
